"""describe change

Revision ID: 13218552e706
Revises: f60c7af1e41d
Create Date: 2025-09-08 00:38:55.863398

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13218552e706'
down_revision = 'f60c7af1e41d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('ibkr_paper_username', sa.String(length=255), nullable=False))
    op.add_column('users', sa.Column('ibkr_paper_password', sa.String(length=255), nullable=False))
    op.add_column('users', sa.Column('ibkr_paper_account_id', sa.String(length=255), nullable=False))
    op.add_column('users', sa.Column('ibkr_live_username', sa.String(length=255), nullable=False))
    op.add_column('users', sa.Column('ibkr_live_password', sa.String(length=255), nullable=False))
    op.add_column('users', sa.Column('ibkr_live_account_id', sa.String(length=255), nullable=False))
    op.drop_column('users', 'ibkr_password')
    op.drop_column('users', 'ibkr_account_id')
    op.drop_column('users', 'ibkr_username')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('ibkr_username', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('ibkr_account_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('ibkr_password', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('users', 'ibkr_live_account_id')
    op.drop_column('users', 'ibkr_live_password')
    op.drop_column('users', 'ibkr_live_username')
    op.drop_column('users', 'ibkr_paper_account_id')
    op.drop_column('users', 'ibkr_paper_password')
    op.drop_column('users', 'ibkr_paper_username')
    # ### end Alembic commands ###


