"""describe change

Revision ID: 6838a72192cb
Revises: bd0ac73b98af
Create Date: 2025-09-15 15:53:40.780001

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '6838a72192cb'
down_revision = 'bd0ac73b98af'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('backtests', 'updated_at')
    op.add_column('trades', sa.Column('option_right', sa.String(length=16), nullable=False))
    op.add_column('trades', sa.Column('expiration', sa.DateTime(), nullable=False))
    op.add_column('trades', sa.Column('strike', sa.Numeric(precision=20, scale=8), nullable=False))
    op.add_column('trades', sa.Column('multiplier', sa.Integer(), nullable=False))
    op.add_column('trades', sa.Column('trade_value', sa.Numeric(precision=20, scale=8), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trades', 'trade_value')
    op.drop_column('trades', 'multiplier')
    op.drop_column('trades', 'strike')
    op.drop_column('trades', 'expiration')
    op.drop_column('trades', 'option_right')
    op.add_column('backtests', sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###


