"""init

Revision ID: a91b38c98cfa
Revises: 
Create Date: 2025-09-05 19:19:42.566407

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a91b38c98cfa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('ibkr_username', sa.String(length=255), nullable=False),
    sa.Column('ibkr_password', sa.String(length=255), nullable=False),
    sa.Column('ibkr_account_id', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('bots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('strategy', sa.String(length=120), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.Column('bot_status', sa.Enum('PENDING', 'BACKTESTING', 'LIVE', 'PAUSED', 'STOPPED', name='bot_status_enum'), nullable=False),
    sa.Column('stop_at', sa.DateTime(), nullable=True),
    sa.Column('paper_trade_return', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('live_trade_return', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bots_name'), 'bots', ['name'], unique=False)
    op.create_index(op.f('ix_bots_owner_id'), 'bots', ['owner_id'], unique=False)
    op.create_table('backtests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('bot_id', sa.String(length=36), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('results', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bot_id'], ['bots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_backtests_bot_id'), 'backtests', ['bot_id'], unique=False)
    op.create_table('trades',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('bot_id', sa.String(length=36), nullable=False),
    sa.Column('event_timestamp', sa.DateTime(), nullable=False),
    sa.Column('order_id', sa.String(length=36), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('assert_type', sa.String(length=36), nullable=False),
    sa.Column('side', sa.String(length=16), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('price', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bot_id'], ['bots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trades_bot_id'), 'trades', ['bot_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trades_bot_id'), table_name='trades')
    op.drop_table('trades')
    op.drop_index(op.f('ix_backtests_bot_id'), table_name='backtests')
    op.drop_table('backtests')
    op.drop_index(op.f('ix_bots_owner_id'), table_name='bots')
    op.drop_index(op.f('ix_bots_name'), table_name='bots')
    op.drop_table('bots')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###


